// <auto-generated />
using System;
using HOPE_13.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HOPE_13.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191202122044_vn1")]
    partial class vn1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HOPE_13.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost");

                    b.Property<string>("Information");

                    b.Property<string>("Nutrition");

                    b.Property<int>("QuantityNight");

                    b.Property<int?>("ToursId");

                    b.Property<string>("TypeOfRooms");

                    b.Property<string>("hotel");

                    b.HasKey("Id");

                    b.HasIndex("ToursId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("HOPE_13.Models.ImageHotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HotelId");

                    b.Property<string>("ImageAdress");

                    b.Property<bool>("isMain");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("ImageHotels");
                });

            modelBuilder.Entity("HOPE_13.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageAdress");

                    b.Property<string>("Tourss");

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("HOPE_13.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HOPE_13.Models.Hotel", b =>
                {
                    b.HasOne("HOPE_13.Models.Tour", "Tours")
                        .WithMany("Hotels")
                        .HasForeignKey("ToursId");
                });

            modelBuilder.Entity("HOPE_13.Models.ImageHotel", b =>
                {
                    b.HasOne("HOPE_13.Models.Hotel", "Hotel")
                        .WithMany("ImageHotels")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
